services:
  infogain_ros2-cpu:
    build:
      context: ../../
      dockerfile: .devcontainer/cpu/Dockerfile
      target: final
    user: ros
    network_mode: host
    ipc: host
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      PULSE_SERVER: ${PULSE_SERVER}
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_SOFTWARE: 1
    volumes:
      - type: bind
        source: ../../
        target: /workspaces/infogain_ros2/
      - type: bind
        source: ../../px4-gazebo-models/
        target: /home/ros/.simulation-gazebo/
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${XDG_RUNTIME_DIR}
        target: ${XDG_RUNTIME_DIR}
        consistency: cached
      - type: bind
        source: ${HOME}/.config/nvim
        target: /home/ros/.config/nvim
      - type: bind
        source: ${HOME}/.ssh
        target: /home/ros/.ssh
        read_only: true
    working_dir: /workspaces/infogain_ros2
    command: tail -f /dev/null
